# Generated by Django 6.1.1 on 2026-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Siraj UPS and Solar', max_length=200)),
                ('subtitle', models.CharField(default='UPS | Solar Systems | Batteries | Inverters | Accessories', max_length=255)),
                ('address', models.TextField(default='Main Market, Shop #12, City Center')),
                ('phone', models.CharField(default='+92 300 1234567', max_length=50)),
                ('whatsapp', models.CharField(default='+92 300 1234567', max_length=50)),
                ('email', models.EmailField(blank=True, default='contact@sirajupssolar.com', max_length=254)),
                ('ntn_number', models.CharField(blank=True, help_text='NTN / Tax Number', max_length=50)),
                ('invoice_footer', models.TextField(default='Thank you for choosing Siraj UPS and Solar! Goods once sold are non-refundable after 7 days.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
            ],
            options={
                'verbose_name': 'Shop Setting',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
