# Generated by Django 6.1.1 on 2026-09-26 12:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_no', models.CharField(max_length=50, unique=True, verbose_name='Service ID')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('service_type', models.CharField(choices=[('UPS_REPAIR', 'UPS Repair'), ('BATTERY_REPLACEMENT', 'Battery Replacement'), ('SOLAR_INSTALLATION', 'Solar Installation'), ('INVERTER_INSTALLATION', 'Inverter Installation'), ('PANEL_INSTALLATION', 'Solar Panel Installation'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other Service')], default='UPS_REPAIR', max_length=50)),
                ('description', models.TextField(help_text='Issue description / job specs')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30)),
                ('parts_materials_used', models.TextField(blank=True)),
                ('labor_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('material_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('OTHER', 'Other')], default='CASH', max_length=30)),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='customers.customer')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
